metadata:
 groupId: org.apache.jclouds.labs
 artifactId: docker
 versioning:
  latest: 1.9.3
  release: 1.9.3
  versions:
   version:
   - 1.8.0
   - 1.8.1
   - 1.9.0
   - 1.9.1
   - 1.9.2
   - 1.9.3
  lastUpdated: '20161123113147'

