metadata:
 groupId: org.jgroups.kubernetes
 artifactId: kubernetes
 versioning:
  latest: 0.9.2
  release: 0.9.2
  versions:
   version:
   - 0.9.0
   - 0.9.1
   - 0.9.2
  lastUpdated: '20170315085221'

