metadata:
 groupId: org.jbundle.config.web
 artifactId: jbundle-config-web-main-site
 versioning:
  latest: 1.3.8
  release: 1.3.8
  versions:
   version:
   - 1.2.6
   - 1.2.7
   - 1.2.8
   - 1.3.0
   - 1.3.5
   - 1.3.6
   - 1.3.7
   - 1.3.8
  lastUpdated: '20130722180952'

