metadata:
 groupId: org.eclipse.neoscada.chart
 artifactId: org.eclipse.scada.chart.swt.sample
 versioning:
  latest: 0.2.0
  release: 0.2.0
  versions:
   version: 0.2.0
  lastUpdated: '20161026205035'

