metadata:
 groupId: org.lyranthe.prometheus
 artifactId: fs2_2.12
 versioning:
  latest: 0.8.4
  release: 0.8.4
  versions:
   version:
   - 0.5.0
   - 0.5.1
   - 0.6.0
   - 0.7.0
   - 0.8.0
   - 0.8.1
   - 0.8.2
   - 0.8.3
   - 0.8.4
  lastUpdated: '20170104115950'

