metadata:
 groupId: org.apache.geronimo.configs
 artifactId: concurrent-deployer
 versioning:
  latest: 2.2.1
  release: 2.2.1
  versions:
   version:
   - '2.2'
   - 2.2.1
  lastUpdated: '20101211142002'

