metadata:
 groupId: org.sakaiproject.deploy
 artifactId: shared-deploy
 versioning:
  latest: '11.3'
  release: '11.3'
  versions:
   version:
   - '11.0'
   - '11.1'
   - '11.2'
   - '11.3'
  lastUpdated: '20170225000000'

