metadata:
 groupId: org.commonjava.indy.docker
 artifactId: indy-test-docker-appliances
 versioning:
  latest: 1.1.4
  release: 1.1.4
  versions:
   version:
   - 1.0.2
   - 1.1.0
   - 1.1.1
   - 1.1.2
   - 1.1.3
   - 1.1.4
  lastUpdated: '20170302000739'

