metadata:
 groupId: org.apache.geronimo.configs
 artifactId: jetty-clustering-builder-wadi
 versioning:
  latest: 1.2-beta
  release: 1.2-beta
  versions:
   version: 1.2-beta
  lastUpdated: '20101014054202'

