metadata:
 groupId: io.wcm.devops.maven
 artifactId: io.wcm.devops.maven.nodejs-proxy
 versioning:
  latest: 1.1.0
  release: 1.1.0
  versions:
   version:
   - 1.0.0
   - 1.1.0
  lastUpdated: '20160322172435'

